destination: ./_site
lsi:         false
port: 4000
highlighter: pygments
markdown:    kramdown
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex

cola_version: "2.0.6"
cola_release_date: "2014-08-30"
cola_downloads: "https://github.com/git-cola/git-cola/releases/download"
cola_archive: "https://github.com/git-cola/git-cola/archive"
cola_github: "https://github.com/git-cola/git-cola"
